# Catthode Theme for Alacritty
# https://cattho.de

[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#b3b3b3"

[colors.cursor]
text = "#000000"
cursor = "#ff9e3b"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ff9e3b"

[colors.search.matches]
foreground = "#000000"
background = "#ffb86c"

[colors.search.focused_match]
foreground = "#000000"
background = "#b9d665"

[colors.footer_bar]
background = "#141414"
foreground = "#b3b3b3"

[colors.hints.start]
foreground = "#000000"
background = "#ffb86c"

[colors.hints.end]
foreground = "#000000"
background = "#b9d665"

[colors.selection]
text = "CellForeground"
background = "#2d2d2d"

[colors.normal]
black = "#141414"
red = "#ff6b6b"
green = "#b9d665"
yellow = "#ffb86c"
blue = "#9cd9e6"
magenta = "#eba4be"
cyan = "#aee6d6"
white = "#b3b3b3"

[colors.bright]
black = "#636363"
red = "#ff6b6b"
green = "#b9d665"
yellow = "#fae2c8"
blue = "#9cd9e6"
magenta = "#eba4be"
cyan = "#aee6d6"
white = "#ffffff"

[colors.dim]
black = "#141414"
red = "#ff6b6b"
green = "#b9d665"
yellow = "#ffb86c"
blue = "#9cd9e6"
magenta = "#eba4be"
cyan = "#aee6d6"
white = "#b3b3b3"
